# permissions for end users to edit logicalreplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pg-replication-operator
    app.kubernetes.io/managed-by: kustomize
  name: logicalreplication-editor-role
rules:
- apiGroups:
  - replication.console.redhat.com
  resources:
  - logicalreplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.console.redhat.com
  resources:
  - logicalreplications/status
  verbs:
  - get
