# permissions for end users to view logicalreplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pg-replication-operator
    app.kubernetes.io/managed-by: kustomize
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  name: logicalreplication-viewer-role
rules:
- apiGroups:
  - replication.console.redhat.com
  resources:
  - logicalreplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replication.console.redhat.com
  resources:
  - logicalreplications/status
  verbs:
  - get
