- op: replace
  path: /metadata/name
  value: subscribing-database
- op: add
  path: /metadata/labels/designation
  value: subscribing
- op: add
  path: /spec/selector/matchLabels/designation
  value: subscribing
- op: add
  path: /spec/template/metadata/labels/designation
  value: subscribing
- op: add
  path: /metadata/labels/designation
  value: subscribing
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: POSTGRESQL_USER
    valueFrom:
      secretKeyRef:
        key: db.user
        name: subscribing-database
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: db.password
        name: subscribing-database
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        key: db.admin_password
        name: subscribing-database
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: POSTGRESQL_MASTER_USER
    valueFrom:
      secretKeyRef:
        key: db.admin_user
        name: subscribing-database
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: POSTGRESQL_MASTER_PASSWORD
    valueFrom:
      secretKeyRef:
        key: db.admin_password
        name: subscribing-database
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: POSTGRESQL_DATABASE
    valueFrom:
      secretKeyRef:
        key: db.name
        name: subscribing-database


